name: Update

on:
  schedule:
    - cron: "0 12 * * 6"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    - run: pip install -r requirements.txt
    - name: Run crawler
      run: python scrape.py
    - name: Add and commit
      id: add_commit
      uses: EndBug/add-and-commit@v9
      with:
        committer_name: Automated
        committer_email: actions@users.noreply.github.com
        message: "Latest data"
